10) Обработка ошибок. Что такое исключение. Исключения в Python.

Задача #1 (try/except):
Написать функцию с именем oops, которая при вызове явно возбуждает исключение IndexError. Затем написать вторую функцию,
вызывающую oops внутри инструкции try/except, которая перехватывает ошибку. Затем изменить функцию oops так, чтобы
вместо IndexError она возбуждала исключение KeyError.

Задача #2 (объекты исключений и списки):
Изменить функцию oops так, чтобы она возбуждала собственное исключение (определить исключение в виде класса). Затем
расширить инструкцию try в функции вызова, так чтобы кроме исключения IndexError она перехватывала новое исключение и
выводила перехваченный экземпляр на экран.

Задача #3 (обработка ошибок):
Написать функцию safe(func, *args), которая запускает указанную функцию func, передавая ей произвольное количество
аргументов с использованием синтаксиса *name, перехватывает любые исключения, возникающие в ходе выполнения функции и
выводит информацию об исключении с использованием функции exc_indo из модуля sys:
- с помощью функции safe запустить функцию oops;
- поместить функцию safe в модуль tools.py и передать ей функцию oops в интерактивном режиме;
- расширить функцию safe так, чтобы при возникновении исключения она выводила содержимое стека вызовов с помощью
  встроенной функции print_ext, расположенной в стандартном модуле traceback.
